import math
from typing import Tuple

import numpy as np


def ess_gen_farina(f_start: int, f_final: int, t_sweep: float, t_idle: float,
                   fs: int, fade_in: int = 0, cut_zerocross: bool = False, sweep_gain: float = 1.0
                   ) -> Tuple[np.ndarray, np.ndarray]:
    """
    Generate a single Exponential Sine Sweep (ESS) and the inverse signal,
    which is used to calculate Room Impulse Responses (RIRs) according to
    Farina [1].

    Parameters
    ----------
        f_start: int
            Starting frequency in Hz.
        f_final: int
            Final frequency in Hz.
        t_sweep: float
            Duration of the sweep in seconds.
        fs: int
            Sampling frequency in Hz.
        fade_in: int, optional
            Number of window length fade in samples. Defaults to zero.
        cut_at_zerocross: bool, optional
            If this flag is set to `True`, cut ESS at the last zero-crossing,
            reducing the signal duration. This is done to prevent abrupt
            termination of the ESS (resulting in pulsive sound). Defaults to
            `False`.
    Returns
    -------
        sweep: np.ndarray
            Generated Exponential Sine Sweep.
        inverse: np.ndarray
            Inverse signal, which is the scaled time-inverse of the ESS.
    """
    R = float(f_final) / f_start
    t = np.arange(0, int(fs * t_sweep)) / fs
    sweep = sweep_gain * np.sin(((2 * math.pi * f_start * t_sweep) / math.log(R)) * (np.power(R, (t / t_sweep)) - 1))

    if (fade_in > 0):
        sweep[0:fade_in] = (sweep[0:fade_in] * np.sin(np.arange(0, fade_in)
                                                      / fade_in * np.pi / 2))

    if (cut_zerocross):
        for idx, sample in enumerate(sweep[::-1]):
            if abs(sample) < 0.001:
                max_freq = (f_start * math.exp((t[-idx-1] / t_sweep) *
                                               math.log(R)))
                print("Warning: sweep cutoff at last zero-crossing. Final "
                      f"frequency is: {np.floor(max_freq)} Hz")
                sweep[-idx:] = np.zeros(idx)
                break

    # Add idle time after ESS
    sweep = np.append(sweep, np.zeros(t_idle * fs))
    return sweep


def ess_parse_farina(measured_sweep: np.ndarray, input_sweep: np.ndarray, t_sweep: float, t_idle: float, fs: int, causality: bool = False) -> np.ndarray:
    """
    Process the input Exponential Sine Sweep (ESS) and output the
    resulting Room Impulse Response (RIR) according to Farina [1].

    Parameters
    ----------
        measured_sweep: np.ndarray
            Measured Exponential Sine Sweep
        input_sweep: np.ndarray
            Ideal input Exponential Sine Sweep (the same as generated by `ess_gen_farina`)
        t_sweep: float
            Duration of the active sweep in seconds.
        t_idle: float
            Idle time in seconds following a single ESS.
        fs: int
            Sampling frequency in Hz
        causality: bool, optional
            If this flag is set to `True`, only return the causal part of the
            RIR. Otherwise, return the full RIR. Defaults to `False`.
    Returns
    -------
        rir: np.ndarray
            The resulting Room Impulse Response.
    """
    if measured_sweep.ndim > 1:
        raise ValueError("Input sweep has more than one dimension. Please input"
                         "a one dimensional vector containing the measured ESS.")
    duration = int(np.floor((t_sweep + t_idle) * fs))

    rir = np.fft.irfft(np.fft.rfft(measured_sweep) / np.fft.rfft(input_sweep))

    if causality:
        rir = rir[int(t_sweep * fs - 1):duration]
    return rir.real